# vim:ft=ansible

---
- hosts: all
  pre_tasks:
    - name: (env) Get ansible_user home directory
      shell: 'getent passwd "{{ansible_ssh_user}}" | cut -d: -f6'
      register: ansible_home_result

  tasks:
    - name: (dotfiles) exist check
      shell: 'test -e "{{ansible_home_result.stdout}}"/.dotfiles'
      register: exist_check
      ignore_errors: yes
    
    
    - name: (dotfiles) git clone
      git:
        repo: 'https://github.com/MaxMEllon/.dotfiles'
        dest: '{{ansible_home_result.stdout}}/.dotfiles'
        version: master
      when: exist_check|failed
    
    - name: (dotfiles) install
      shell: 'cd "{{ansible_home_result.stdout}}"/.dotfiles && bash init.sh "{{ansible_home_result.stdout}}"/.dotfiles'
