# vim:ft=ansible

---
- hosts: all
  tasks:
    - name: (dotfiles) exist check
      shell: 'test -e "{{ansible_env.HOME}}"/.dotfiles'
      register: exist_check
      ignore_errors: yes
    
    
    - name: (dotfiles) git clone
      git:
        repo: 'https://github.com/MaxMEllon/.dotfiles'
        dest: '{{ansible_env.HOME}}/.dotfiles'
        version: master
      when: exist_check|failed
    
    - name: (dotfiles) install
      shell: 'cd "{{ansible_env.HOME}}"/.dotfiles && bash init.sh "{{ansible_env.HOME}}"/.dotfiles'
